# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Kristen Faith
# Description of the Site
description: Musician and Singer/Songwriter
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/main_profile.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kristenfaith.17@gmail.com
facebook_username: thedevslot
instagram_username: thedevslot
tiktok_username: 
youtube_channel_id: 

twitter_username: 
linkedin_username: 
github_username:  
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Kristen Faith
# URL for the Image of the Author
author-image: /assets/images/main_profile.png
# 60 Words About the Author
author-about: She is a self taught musician with a passion for song-writing and a heart to be heard. Her musical style has influence from her early days in church and a loving and talented father. This is just the beginning of her story.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot
albums:
  never_gave_up_on_me:
    img: /assets/images/never_gave_up_on_me.JPG
    description: <i>Never Gave Up On Me</i> is Kristen Faith’s first single, inspired by life events that took her down to her lowest place which led to her most impactful come back. Her Pastor, at the time, would constantly share the message “God is not mad at you, but MAD ABOUT YOU.” That message would echo in her mind as she navigated hurt, condemnation, and shame after yet another fail in her life. Never Gave Up On Me is her anthem to those years spent chasing acceptance and perfection. 


# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
